config/routes.rb
Rails.application.routes.draw do
  root to: 'longestword#game'
  get 'game', to: 'longestword#game'
  get 'score', to: 'longestword#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def game
    @grid = generate_grid(9)
    @start_time = Time.now
  end

  def score
    end_time = Time.now
    @result = run_game(params[:word], params[:grid].split(''), DateTime.strptime(params[:start_time], '%Y-%m-%d %H:%M:%S %z'), end_time)
    @result[:attempt] = params[:word]
  end



  def generate_grid(grid_size)
    return Array.new(grid_size) { ('A'..'Z').to_a[rand(26)] }
  end



  def score_and_message(attempt, translation, grid, time)
    if included?(attempt.upcase, grid)
      if translation
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not a word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def compute_score(attempt, time_taken)
    (time_taken > 60.0) ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def included?(guess, grid)
    guess.split('').each { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: (end_time - start_time).round }

    result[:translation] = get_translation(attempt)
    result[:score], result[:message] = score_and_message(
      attempt, result[:translation], grid, result[:time])
    return result
  end
end

app/controllers/longestword_controller.rb
class LongestwordController < ApplicationController
  def game
    @start_time = Time.now
    @grid = generate_grid(9).join(' ')
  end

  def score
    @end_time = Time.now
    @attempt = params[:attempt]
    @grid = params[:grid]
    @result = run_game(params[:attempt], @grid.split(' '), Time.parse(params[:start_time]), @end_time)
  end

  private
    def generate_grid(grid_size)
      Array.new(grid_size) { ('A'..'Z').to_a[rand(26)] }
    end
    def included?(guess, grid)
      guess.chars.all? { |letter| guess.count(letter) <= grid.count(letter) }
    end
    def compute_score(attempt, time_taken)
      (time_taken > 60.0) ? 0 : attempt.size * (1.0 - time_taken / 60.0)
    end
    def run_game(attempt, grid, start_time, end_time)
      result = { time: end_time - start_time }
      result[:translation] = get_translation(attempt)
      result[:score], result[:message] = score_and_message(
        attempt, result[:translation], grid, result[:time])
      result
    end
    def score_and_message(attempt, translation, grid, time)
      if included?(attempt.upcase, grid)
        if translation
          score = compute_score(attempt, time)
          [score, "Good Job!"]
        else
          [0, "This is not a word!"]
        end
      else
        [0, "One of the letters you typed is not in the grid!"]
      end
    end
    def get_translation(word)
      api_key = "YOUR_SYSTRAN_API_KEY"
      begin
        response = open("https://api-platform.systran.net/translation/text/translate?source=en&target=fr&key=#{api_key}&input=#{word}")
        json = JSON.parse(response.read.to_s)
        if json['outputs'] && json['outputs'][0] && json['outputs'][0]['output'] && json['outputs'][0]['output'] != word
          return json['outputs'][0]['output']
        end
      rescue
        if File.read('/usr/share/dict/words').upcase.split("\n").include? word.upcase
          return word
        else
          return nil
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/longestword_helper.rb
module LongestwordHelper
end

app/views/games/game.html.erb
<!-- <h1>Games#game</h1>
<p>Find me in app/views/games/game.html.erb</p>
 -->
<div class="wrapper-img">
  <div class="container text-center">
    <h1>Welcome to the longest word-game</h1>
    <p>Here is your grid: </p>

      <table class="letter-table">
        <tr>
          <% @grid.each do |letter| %>
            <td><%= letter %></td>
          <% end %>
        </tr>
      </table>
    <form action="/score">
      <div class="form-group">
        <label>Enter the longest word in the grid</label>
        <input type="text" name="word" class="form-control">
        <input type="hidden" name="start_time" class="form-control" value="<%= @start_time %>">
        <input type="hidden" name="grid" class="form-control" value="<%= @grid %>">
      </div>
      <input type="submit" class="btn btn-primary btn-lg" value="Submit your word!">
    </form>
  </div>
</div>

app/views/games/score.html.erb
<!-- <h1>Games#score</h1>
<p>Find me in app/views/games/score.html.erb</p>

 -->
<div class="wrapper-img">
  <div class="container text-center">
    <h1>Your result</h1>

    <table class="score-table">
      <thead>
        <th>Your word</th>
        <th>Time taken to answer</th>
        <th>Translation</th>
        <th>Your score</th>
        <th>Message</th>
      </thead>
      <tbody>
        <td><%= @result[:attempt]%></td>
        <td><%= @result[:time]%>s</td>
        <td><%= @result[:translation]%></td>
        <td><%= @result[:score].round%></td>
        <td><%= @result[:message]%></td>
      </tbody>
    </table>

    <div class="row">
      <%= link_to "Play again!", game_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/longestword/game.html.erb
h1>THIS IS THE LONGEST WORD GAME!</h1>
<h2>Here is your grid:</h2>
<p><%= @grid %><p>
<form action="/score">
  <input type="text" id="question" name="attempt" placeholder="what is your word?">
  <input type="hidden" name="start_time" value="<%= @start_time %>">
  <input type="hidden" name="grid" value="<%= @grid%>">
  <input type="submit" value="Go on!">
</form>

app/views/longestword/score.html.erb
<!-- <h1>LongestWord#score</h1>
<p>Find me in app/views/longest_word/score.html.erb</p>
 -->
<h1>You entered the word:<%= @attempt %></h1>
<p>Answer Time: <%=@result[:time]%></p>
<p>Translation: <%=@result[:translation]%></p>
<p>Your score: <%=@result[:score]%></p>
<p>Feedback: <%=@result[:message]%></p>
Add Comment